-- UMBRA Phase 2 — real-money payments (Unipesa). Run this once in the Supabase
-- SQL editor (Dashboard -> SQL -> New query), after db/schema.sql.
--
-- The server (SERVICE ROLE key) is the only writer/reader; clients get NO access
-- (RLS on, no policies). Money is only ever moved through the append-only
-- umbra_ledger — these tables are the payment lifecycle + audit trail.

-- ── every deposit / withdrawal, keyed by the gateway order_id ────────────────
create table if not exists public.umbra_payments (
  order_id      text        primary key,           -- dep_… / wd_… (idempotency key)
  account       text        not null,              -- Supabase user id
  kind          text        not null,              -- 'deposit' | 'withdrawal'
  amount        bigint      not null,              -- integer CDF
  provider      text        not null,              -- vodacom | orange | airtel | africell | simulator
  provider_id   integer     not null,
  phone         text        not null,
  status        integer     not null default 0,    -- Unipesa status (0..6)
  status_label  text,
  settled       boolean     not null default false,-- terminal (money applied/refunded)
  credited      boolean     not null default false,-- deposit only: Credit added
  confirm_type  integer     not null default 0,
  message       text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists umbra_payments_account_idx on public.umbra_payments (account, created_at desc);
create index if not exists umbra_payments_open_idx    on public.umbra_payments (settled, created_at) where settled = false;

-- ── raw callback audit trail (stored BEFORE processing, valid or not) ─────────
create table if not exists public.umbra_callbacks (
  id          bigint generated by default as identity primary key,
  order_id    text,
  valid       boolean not null,
  raw         jsonb   not null,
  received_at timestamptz not null default now()
);
create index if not exists umbra_callbacks_order_idx on public.umbra_callbacks (order_id);

-- ── one-time 18+/Terms attestation (immutable once set) ───────────────────────
create table if not exists public.umbra_compliance (
  account       text        primary key,
  attested_at   timestamptz not null default now(),
  terms_version text        not null default '1'
);

-- ── lock clients out: RLS on, no policies -> only the service role touches these
alter table public.umbra_payments   enable row level security;
alter table public.umbra_callbacks  enable row level security;
alter table public.umbra_compliance enable row level security;
